In [2]:
!pip install pandas

Collecting pandas
  Downloading pandas-1.5.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 7.0 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas) (2022.7.1)
Collecting numpy>=1.21.0
  Downloading numpy-1.24.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 5.9 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/conda/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Installing collected packages: numpy, pandas
Successfully installed numpy-1.24.2 pandas-1.5.3

In [5]:
import pandas as pd
import json

In [6]:
data = json.load(open('mpd.slice.1000-1999.json'))

In [13]:
playlists=data['playlists']

In [25]:
df = pd.DataFrame.from_dict(playlists)
df.head(5)

,name,collaborative,pid,modified_at,num_tracks,num_albums,num_followers,tracks,num_edits,duration_ms,num_artists,description
0,disney,false,1000,1457827200,189,16,1,"[{'pos': 0, 'artist_name': 'Original Broadway ...",4,31428282,65,NaN
1,Indie Electro,false,1001,1417824000,165,18,2,"[{'pos': 0, 'artist_name': 'The Octopus Projec...",2,38241566,8,NaN
2,jack & jack,false,1002,1465430400,17,14,1,"[{'pos': 0, 'artist_name': 'Jack & Jack', 'tra...",3,3549358,3,NaN
3,vibes,false,1003,1498435200,225,195,2,"[{'pos': 0, 'artist_name': 'LANY', 'track_uri'...",91,51242585,157,NaN
4,Indie,false,1004,1498608000,165,118,1,"[{'pos': 0, 'artist_name': 'Youth Lagoon', 'tr...",74,42601098,92,NaN

In [21]:
columnas=df['tracks'][1][0].keys()
#para obtener los datos de artista, album, 
#track se tiene que extraer del array que está dentro de las tracks de cada una,
#para luego pbtener cada uno.
columnas

dict_keys(['pos', 'artist_name', 'track_uri', 'artist_uri', 'track_name', 'album_uri', 'duration_ms', 'album_name'])

In [24]:
dffull = pd.DataFrame(columns=columnas)
dffull

Empty DataFrame
Columns: [pos, artist_name, track_uri, artist_uri, track_name, album_uri, duration_ms, album_name]
Index: []

In [26]:
#se trabajrea con 5 playlist por ahora
df=df.head(5)
df

,name,collaborative,pid,modified_at,num_tracks,num_albums,num_followers,tracks,num_edits,duration_ms,num_artists,description
0,disney,false,1000,1457827200,189,16,1,"[{'pos': 0, 'artist_name': 'Original Broadway ...",4,31428282,65,NaN
1,Indie Electro,false,1001,1417824000,165,18,2,"[{'pos': 0, 'artist_name': 'The Octopus Projec...",2,38241566,8,NaN
2,jack & jack,false,1002,1465430400,17,14,1,"[{'pos': 0, 'artist_name': 'Jack & Jack', 'tra...",3,3549358,3,NaN
3,vibes,false,1003,1498435200,225,195,2,"[{'pos': 0, 'artist_name': 'LANY', 'track_uri'...",91,51242585,157,NaN
4,Indie,false,1004,1498608000,165,118,1,"[{'pos': 0, 'artist_name': 'Youth Lagoon', 'tr...",74,42601098,92,NaN

In [ ]:
##borrando 
dftfull = pd.DataFrame(columns=df['tracks'][0][0].keys())

for index, row in df.iterrows():
    print(row['name'], row['pid'],row['num_tracks'])
    for row2 in row['tracks']:
      dftemp = pd.DataFrame(row2,index=[0])
      dffull = dffull.append(dftemp)

In [37]:
dffull # se tienen todas las canciones juntas

,pos,artist_name,track_uri,artist_uri,track_name,album_uri,duration_ms,album_name
0,0,Original Broadway Cast - The Little Mermaid,spotify:track:5IbCV9Icebx8rR6wAp5hhP,spotify:artist:3TymzPhJTMyupk7P5xkahM,Fathoms Below - Broadway Cast Recording,spotify:album:3ULJeOMgroG27dpn27MDfS,154506,The Little Mermaid: Original Broadway Cast Rec...
0,1,Original Broadway Cast - The Little Mermaid,spotify:track:6rKVAvjHcxAzZ1BHtwh5yC,spotify:artist:3TymzPhJTMyupk7P5xkahM,Daughters Of Triton - Broadway Cast Recording,spotify:album:3ULJeOMgroG27dpn27MDfS,79066,The Little Mermaid: Original Broadway Cast Rec...
0,2,Original Broadway Cast - The Little Mermaid,spotify:track:6Jlkb1Wh08RYHstWScsTvg,spotify:artist:3TymzPhJTMyupk7P5xkahM,The World Above - Broadway Cast Recording,spotify:album:3ULJeOMgroG27dpn27MDfS,94600,The Little Mermaid: Original Broadway Cast Rec...
0,3,Original Broadway Cast - The Little Mermaid,spotify:track:0XhC8bfStML9ygBmfOt1JJ,spotify:artist:3TymzPhJTMyupk7P5xkahM,Human Stuff - Broadway Cast Recording,spotify:album:3ULJeOMgroG27dpn27MDfS,151480,The Little Mermaid: Original Broadway Cast Rec...
0,4,Original Broadway Cast - The Little Mermaid,spotify:track:0ABxAcsRWlqckkyONsfP67,spotify:artist:3TymzPhJTMyupk7P5xkahM,I Want the Good Times Back - Broadway Cast Rec...,spotify:album:3ULJeOMgroG27dpn27MDfS,297920,The Little Mermaid: Original Broadway Cast Rec...
...,...,...,...,...,...,...,...,...
0,160,Weekend Affair,spotify:track:3wOeFpaSQUi1wDeiecDUod,spotify:artist:0dZXa7OgcOzv3tNUagbKb7,I Walk Alone,spotify:album:6FvbZMdqvXSGIwaFXPthuE,237280,Welcome to Your Fate
0,161,Weekend Affair,spotify:track:3WLS3HQcz3t3d5GLPDZkcZ,spotify:artist:0dZXa7OgcOzv3tNUagbKb7,Try Again,spotify:album:6FvbZMdqvXSGIwaFXPthuE,211000,Welcome to Your Fate
0,162,Jack Garratt,spotify:track:6vRp1EGkh1SE7uGNhbqVjT,spotify:artist:1Zp054Jc86WVKCxKEqZGOA,Surprise Yourself,spotify:album:4neDtPlGoWdcLZsedOGN5E,260866,Phase
0,163,The Beach Boys,spotify:track:58TvuKjnOZK7mZp680GnqH,spotify:artist:3oDbviiivRWhXwIE8hxkVV,God Only Knows - Mono,spotify:album:42oBdomfxF0DbKKMEqrnQW,173560,Pet Sounds
0,164,Timber Timbre,spotify:track:3kpRgTtMnArQ5Gay0JxElf,spotify:artist:7HeVXdOdMhLslVputGTZFQ,Hot Dreams,spotify:album:2U1BUKvsYIkUik7xEhAP0C,293213,Hot Dreams