In [2]:
!pip install pandas

Collecting pandas
  Downloading pandas-1.5.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 7.0 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas) (2022.7.1)
Collecting numpy>=1.21.0
  Downloading numpy-1.24.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 5.9 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/conda/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Installing collected packages: numpy, pandas
Successfully installed numpy-1.24.2 pandas-1.5.3

In [1]:
import pandas as pd
import json

In [2]:
data = json.load(open('mpd.slice.1000-1999.json'))

In [3]:
playlists=data['playlists']

In [4]:
df = pd.DataFrame.from_dict(playlists)
df.head(5)

,name,collaborative,pid,modified_at,num_tracks,num_albums,num_followers,tracks,num_edits,duration_ms,num_artists,description
0,disney,false,1000,1457827200,189,16,1,"[{'pos': 0, 'artist_name': 'Original Broadway ...",4,31428282,65,NaN
1,Indie Electro,false,1001,1417824000,165,18,2,"[{'pos': 0, 'artist_name': 'The Octopus Projec...",2,38241566,8,NaN
2,jack & jack,false,1002,1465430400,17,14,1,"[{'pos': 0, 'artist_name': 'Jack & Jack', 'tra...",3,3549358,3,NaN
3,vibes,false,1003,1498435200,225,195,2,"[{'pos': 0, 'artist_name': 'LANY', 'track_uri'...",91,51242585,157,NaN
4,Indie,false,1004,1498608000,165,118,1,"[{'pos': 0, 'artist_name': 'Youth Lagoon', 'tr...",74,42601098,92,NaN

In [5]:
columnas=df['tracks'][1][0].keys()
#para obtener los datos de artista, album, 
#track se tiene que extraer del array que está dentro de las tracks de cada una,
#para luego pbtener cada uno.
columnas

dict_keys(['pos', 'artist_name', 'track_uri', 'artist_uri', 'track_name', 'album_uri', 'duration_ms', 'album_name'])

In [6]:
dffull = pd.DataFrame(columns=columnas)
dffull

Empty DataFrame
Columns: [pos, artist_name, track_uri, artist_uri, track_name, album_uri, duration_ms, album_name]
Index: []

In [7]:
#se trabajrea con 5 playlist por ahora
# df=df.head(5)
df

,name,collaborative,pid,modified_at,num_tracks,num_albums,num_followers,tracks,num_edits,duration_ms,num_artists,description
0,disney,false,1000,1457827200,189,16,1,"[{'pos': 0, 'artist_name': 'Original Broadway ...",4,31428282,65,NaN
1,Indie Electro,false,1001,1417824000,165,18,2,"[{'pos': 0, 'artist_name': 'The Octopus Projec...",2,38241566,8,NaN
2,jack & jack,false,1002,1465430400,17,14,1,"[{'pos': 0, 'artist_name': 'Jack & Jack', 'tra...",3,3549358,3,NaN
3,vibes,false,1003,1498435200,225,195,2,"[{'pos': 0, 'artist_name': 'LANY', 'track_uri'...",91,51242585,157,NaN
4,Indie,false,1004,1498608000,165,118,1,"[{'pos': 0, 'artist_name': 'Youth Lagoon', 'tr...",74,42601098,92,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
995,woo,false,1995,1509062400,146,68,2,"[{'pos': 0, 'artist_name': 'blink-182', 'track...",13,29183178,24,NaN
996,NEW YEARS,false,1996,1420070400,38,37,1,"[{'pos': 0, 'artist_name': 'Big Sean', 'track_...",3,9354755,34,NaN
997,JESUS,false,1997,1508371200,40,28,2,"[{'pos': 0, 'artist_name': 'Elevation Worship'...",8,10940019,22,NaN
998,yep,false,1998,1448236800,29,27,1,"[{'pos': 0, 'artist_name': 'Oasis', 'track_uri...",3,7260645,20,NaN
999,Sad Music,false,1999,1464307200,16,14,1,"[{'pos': 0, 'artist_name': 'blink-182', 'track...",3,3701742,12,NaN

In [8]:
##borrando 
dffull = pd.DataFrame(columns=columnas)
dffull

Empty DataFrame
Columns: [pos, artist_name, track_uri, artist_uri, track_name, album_uri, duration_ms, album_name]
Index: []

In [9]:
import warnings
warnings.filterwarnings('ignore')
## https://softhints.com/turn-off-warnings-jupyterlab-jupyter-notebook/

In [10]:
for index, row in df.iterrows():
    #print(row['name'], row['pid'],row['num_tracks'])
    for row2 in row['tracks']:
      dftemp = pd.DataFrame(row2,index=[0])
      dffull = dffull.append(dftemp)

In [11]:
dffull # se tienen todas las canciones juntas

,pos,artist_name,track_uri,artist_uri,track_name,album_uri,duration_ms,album_name
0,0,Original Broadway Cast - The Little Mermaid,spotify:track:5IbCV9Icebx8rR6wAp5hhP,spotify:artist:3TymzPhJTMyupk7P5xkahM,Fathoms Below - Broadway Cast Recording,spotify:album:3ULJeOMgroG27dpn27MDfS,154506,The Little Mermaid: Original Broadway Cast Rec...
0,1,Original Broadway Cast - The Little Mermaid,spotify:track:6rKVAvjHcxAzZ1BHtwh5yC,spotify:artist:3TymzPhJTMyupk7P5xkahM,Daughters Of Triton - Broadway Cast Recording,spotify:album:3ULJeOMgroG27dpn27MDfS,79066,The Little Mermaid: Original Broadway Cast Rec...
0,2,Original Broadway Cast - The Little Mermaid,spotify:track:6Jlkb1Wh08RYHstWScsTvg,spotify:artist:3TymzPhJTMyupk7P5xkahM,The World Above - Broadway Cast Recording,spotify:album:3ULJeOMgroG27dpn27MDfS,94600,The Little Mermaid: Original Broadway Cast Rec...
0,3,Original Broadway Cast - The Little Mermaid,spotify:track:0XhC8bfStML9ygBmfOt1JJ,spotify:artist:3TymzPhJTMyupk7P5xkahM,Human Stuff - Broadway Cast Recording,spotify:album:3ULJeOMgroG27dpn27MDfS,151480,The Little Mermaid: Original Broadway Cast Rec...
0,4,Original Broadway Cast - The Little Mermaid,spotify:track:0ABxAcsRWlqckkyONsfP67,spotify:artist:3TymzPhJTMyupk7P5xkahM,I Want the Good Times Back - Broadway Cast Rec...,spotify:album:3ULJeOMgroG27dpn27MDfS,297920,The Little Mermaid: Original Broadway Cast Rec...
...,...,...,...,...,...,...,...,...
0,11,Seether,spotify:track:2G8gLafzmoHwa6RBih74J3,spotify:artist:6B5c4sch27tWHAGdarpPaW,Broken - Featuring Amy Lee,spotify:album:5qHjA0aU9vt9c2UwDeEGjS,258333,Disclaimer II
0,12,Three Days Grace,spotify:track:1bPRhOz3nOfEIoLjB1YYT3,spotify:artist:2xiIXseIJcq3nG7C8fHeBj,No More,spotify:album:0vv1zKShlm7WuawEup5Mf4,225493,Life Starts Now
0,13,Three Days Grace,spotify:track:1o4Pf2GIMDCD7ifIM2yI77,spotify:artist:2xiIXseIJcq3nG7C8fHeBj,Last to Know,spotify:album:0vv1zKShlm7WuawEup5Mf4,207466,Life Starts Now
0,14,3 Doors Down,spotify:track:0nNVR2iDM3eVzEgMi78vQm,spotify:artist:2RTUTCvo6onsAnheUk3aL9,Let Me Go,spotify:album:44AVPs6VGKnZHinQNWd6Xd,243053,The Greatest Hits
0,15,Tech N9ne Collabos,spotify:track:6XzJXUQpwPkp8g5KW9TRoP,spotify:artist:4UOlRVifrFdQHW9qu5ep8t,Actin Like You Know,spotify:album:3WyX9z5XQxk8X5HZdnbzJi,239928,Strangeulation Vol. II (Deluxe Edition)

In [12]:
uartist = dffull['artist_uri'].unique()
## uartist

In [13]:
dffull[dffull["artist_uri"]=='spotify:artist:3TymzPhJTMyupk7P5xkahM'].iloc[0]

pos                                                            0
artist_name          Original Broadway Cast - The Little Mermaid
track_uri                   spotify:track:5IbCV9Icebx8rR6wAp5hhP
artist_uri                 spotify:artist:3TymzPhJTMyupk7P5xkahM
track_name               Fathoms Below - Broadway Cast Recording
album_uri                   spotify:album:3ULJeOMgroG27dpn27MDfS
duration_ms                                               154506
album_name     The Little Mermaid: Original Broadway Cast Rec...
Name: 0, dtype: object

In [14]:
##crear un df de artist vacio
dfartist = pd.DataFrame(columns=["sk_id","bk_id","name"]) 

rownum=1
for row in uartist:
  ##print(dffull[dffull.artist_uri == row].iloc[0]["artist_uri"],dffull[dffull.artist_uri == row].iloc[0]['artist_name'])

##https://vitalflux.com/pandas-dataframe-how-to-add-rows-columns/#:~:text=There%20are%20multiple%20ways%20of,use%20Dataframe.insert()%20method.
  dftemp = pd.DataFrame({
      "sk_id":rownum,
      "bk_id":dffull[dffull.artist_uri == row].iloc[0]["artist_uri"],
      "name":dffull[dffull.artist_uri == row].iloc[0]["artist_name"]
      },index=[0])
  dfartist=dfartist.append(dftemp)

  rownum = rownum + 1

In [15]:
dfartist

,sk_id,bk_id,name
0,1,spotify:artist:3TymzPhJTMyupk7P5xkahM,Original Broadway Cast - The Little Mermaid
0,2,spotify:artist:1j4a3bBWYNjecFqxcjRtr5,Sierra Boggess as Ariel
0,3,spotify:artist:5sy77gt4bfsLcSQ8GIe4ZZ,Alan Menken
0,4,spotify:artist:1RJ9qwSsCfnOcTXBSqotNk,Ariel
0,5,spotify:artist:6Id8rcDNyBXPcgKQVfQ8rX,Samuel E. Wright
...,...,...,...
0,10299,spotify:artist:3tM6SwRysCaIK0kW4h0mVP,Spose
0,10300,spotify:artist:4qUFkkArfii3qNG8TnbPfc,Masked Intruder
0,10301,spotify:artist:7C64wNX3howEFZjAYRKsfP,The Cataracs
0,10302,spotify:artist:6pxwzi0xDny2rMI1KJFZoi,Young T.H.U.G.
0,10303,spotify:artist:2HHIJKrqm8CEnlKlv5gIHI,The Royal Viena Orchestra

In [16]:
## lo mismo para albums
ualbum = dffull['album_uri'].unique()
# ualbum

In [17]:
##crear un df de album vacio
dfalbum = pd.DataFrame(columns=["sk_id","bk_id","name"]) 

rownum=1
for row in ualbum:
  dftemp = pd.DataFrame({
      "sk_id":rownum,
      "bk_id":dffull[dffull.album_uri == row].iloc[0]["album_uri"],
      "name":dffull[dffull.album_uri == row].iloc[0]["album_name"]
      },index=[0])
  dfalbum=dfalbum.append(dftemp)

  rownum = rownum + 1

In [18]:
dfalbum

,sk_id,bk_id,name
0,1,spotify:album:3ULJeOMgroG27dpn27MDfS,The Little Mermaid: Original Broadway Cast Rec...
0,2,spotify:album:4aAwvCRNJIqiUGVEjieWv6,Little Mermaid
0,3,spotify:album:5wqx6PBsow0KIQrnu9xd6c,Aladdin Original Broadway Cast Recording
0,4,spotify:album:6fBzYwBKjuO4hmhcGuklJM,Tarzan Original Soundtrack
0,5,spotify:album:6DnTzVKb79zEtICWeIB2El,Beauty And The Beast: The Broadway Musical
...,...,...,...
0,20208,spotify:album:5UnaAIuMRqSBeBWY3XM0FQ,American Prodigal
0,20209,spotify:album:77yXUMeh96foFhIR2aK3Fb,De Cine
0,20210,spotify:album:3nta4nhqWoWjc6LmHIB0kT,Verities & Balderdash
0,20211,spotify:album:5G6pS4ES22Np0hehqJYIct,Title Of Record
0,20212,spotify:album:3WyX9z5XQxk8X5HZdnbzJi,Strangeulation Vol. II (Deluxe Edition)

In [21]:
## lo mismo para tracks
utrack = dffull['track_uri'].unique()
utrack

array(['spotify:track:5IbCV9Icebx8rR6wAp5hhP',
       'spotify:track:6rKVAvjHcxAzZ1BHtwh5yC',
       'spotify:track:6Jlkb1Wh08RYHstWScsTvg', ...,
       'spotify:track:1bPRhOz3nOfEIoLjB1YYT3',
       'spotify:track:1o4Pf2GIMDCD7ifIM2yI77',
       'spotify:track:6XzJXUQpwPkp8g5KW9TRoP'], dtype=object)

In [20]:
##crear un df de track vacio
dftrack = pd.DataFrame(columns=["sk_id","bk_id","name"]) 

rownum=1
for row in utrack:
  dftemp = pd.DataFrame({
      "sk_id":rownum,
      "bk_id":dffull[dffull.track_uri == row].iloc[0]["track_uri"],
      "name":dffull[dffull.track_uri == row].iloc[0]["track_name"]
      },index=[0])
  dftrack=dftrack.append(dftemp)

  rownum = rownum + 1

In [22]:
dftrack

,sk_id,bk_id,name
0,1,spotify:track:5IbCV9Icebx8rR6wAp5hhP,Fathoms Below - Broadway Cast Recording
0,2,spotify:track:6rKVAvjHcxAzZ1BHtwh5yC,Daughters Of Triton - Broadway Cast Recording
0,3,spotify:track:6Jlkb1Wh08RYHstWScsTvg,The World Above - Broadway Cast Recording
0,4,spotify:track:0XhC8bfStML9ygBmfOt1JJ,Human Stuff - Broadway Cast Recording
0,5,spotify:track:0ABxAcsRWlqckkyONsfP67,I Want the Good Times Back - Broadway Cast Rec...
...,...,...,...
0,36171,spotify:track:2c5wml8wsBnPfNSbCZ574T,Take a Picture
0,36172,spotify:track:3bq8WiQrEXMwPAibYs7tpu,Nobody Praying For Me
0,36173,spotify:track:1bPRhOz3nOfEIoLjB1YYT3,No More
0,36174,spotify:track:1o4Pf2GIMDCD7ifIM2yI77,Last to Know
0,36175,spotify:track:6XzJXUQpwPkp8g5KW9TRoP,Actin Like You Know

In [ ]:
##todo inserta a base de datos postgresql
## 1. d_albums desde dfalbum
## 2. d_artists desde dfartist
## 3. d_tracks  desde dftrack
## 4 insertar a d_playlists desde df
## 5 insertar a d_playlist_Tracks desde dffull

In [27]:
## exportar datos transformados a csv como plan B para agregar a Postgres
dfalbum.to_csv("albums.csv",index=False)
dfartist.to_csv("artists.csv",index=False)
dftrack.to_csv("tracks.csv",index=False)
df.to_csv("playlists.csv",index=False)
dffull.to_csv("playlist_tracks.csv",index=False)

In [108]:
##instalar conexion python a postgresql
!pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in /opt/conda/lib/python3.10/site-packages (2.9.5)

In [110]:
## insertar albums
## revisar el dataframe 
dfalbum.head()

,sk_id,bk_id,name
0,1,spotify:album:3ULJeOMgroG27dpn27MDfS,The Little Mermaid: Original Broadway Cast Rec...
0,2,spotify:album:4aAwvCRNJIqiUGVEjieWv6,Little Mermaid
0,3,spotify:album:5wqx6PBsow0KIQrnu9xd6c,Aladdin Original Broadway Cast Recording
0,4,spotify:album:6fBzYwBKjuO4hmhcGuklJM,Tarzan Original Soundtrack
0,5,spotify:album:6DnTzVKb79zEtICWeIB2El,Beauty And The Beast: The Broadway Musical